name: Postman API Tests

on:
  push:
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Postman tests
        run: |
          mkdir -p projects/postman-api-ci-github-actions/reports

          newman run projects/postman-api-ci-github-actions/postman-api-ci-cd.postman_collection.json \
            --reporters cli,json,htmlextra \
            --reporter-json-export projects/postman-api-ci-github-actions/reports/results.json \
            --reporter-htmlextra-export projects/postman-api-ci-github-actions/reports/report.html

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: postman-test-reports
          path: projects/postman-api-ci-github-actions/reports/
